### ISSUE TITLE
Copy local issues

### ISSUE THREAD

**Issue by sayedihashimi** [sayedihashimi/slow-cheetah#15] opened 2012-06-07 21:31 UTC
When a transform is added if the source file is marked to copy local there are issues in that the original file may be copied on top of the transformed file. This should be fixed but we need to ensure that the source file is copied to the output directory for build configurations which do not have an associated transform.

**Comment by davilimap** [comment] 2017-02-24 19:11
Duplicate of #171. Will keep the most recent issue to track this.

**Closed by davilimap** 2017-02-24 19:11 UTC
Labels: bug, duplicate, P0
